# Use a Microsoft VS Code development container Python image
# As of 2024-01-02 Tensorflow requires 3.11
FROM mcr.microsoft.com/devcontainers/python:3.11






COPY Model/requirements.txt /tmp/pip-tmp/
RUN pip --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt && rm -rf /tmp/pip-tmp

